- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "Creates directory"
  file:
    path: ~/web
    state: directory


- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes


- name: "Executing node"
  shell: |
     sudo npm i -g pm2
     pm2 start ~/web/index.js -f